version: '3.9'

services:
  apache:
    image: httpd
    ports:
      - "8080:80"
    volumes:
      - ./public-html:/usr/local/apache2/htdocs/
    networks:
      - mynet 

volumes:
  public-html:

networks:
  mynet:
    driver: bridge